// Placeholder — replace with types generated by:
// npx supabase gen types typescript --local > types/index.ts
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type UserProfile = {
  id: string
  email: string
  full_name: string | null
  locale: string
  created_at: string
  updated_at: string
}

export type Subscription = {
  id: string
  user_id: string
  stripe_customer_id: string
  stripe_subscription_id: string | null
  status: string
  plan_id: string | null
  current_period_end: string | null
  created_at: string
  updated_at: string
}
